#!/usr/bin/env python3
"""Run the two requested UWB reproductions on measurements generated by CARLA."""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "code" / "analysis"))
sys.path.insert(0, str(REPO_ROOT / "simulation"))

from algorithms.router import AlgorithmRouter, register_default_algorithms
from algorithms.uwb.real_data import reset_runner_state
from evaluation.metrics import position_metrics, success_metrics
from generators.range_simulation import Anchor, simulate_ranges


ALGORITHMS = (
    "uwb.matlab.trilateration",
    "uwb.matlab.multilateration",
    "uwb.matlab.taylor",
    "uwb.matlab.ekf",
    "uwb.matlab.ukf",
    "uwb.awesome_uwb",
)


def _parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=2000)
    parser.add_argument("--frames", type=int, default=100)
    parser.add_argument("--warmup-frames", type=int, default=20)
    parser.add_argument("--fixed-delta-seconds", type=float, default=0.1)
    parser.add_argument("--sigma-m", type=float, default=0.05)
    parser.add_argument("--random-seed", type=int, default=42)
    parser.add_argument("--anchor-half-width-m", type=float, default=15.0)
    parser.add_argument("--anchor-half-height-m", type=float, default=12.0)
    parser.add_argument(
        "--anchor-heights-m", default="0.5,4.5,0.5,4.5",
        help="four comma-separated anchor heights in the local ground frame",
    )
    parser.add_argument("--uav-altitude-m", type=float, default=3.0)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=REPO_ROOT / "outputs" / "carla_uwb_reproduction",
    )
    args = parser.parse_args(argv)
    if args.frames < 10 or args.warmup_frames < 0:
        parser.error("frames must be >= 10 and warmup-frames must be non-negative")
    if args.fixed_delta_seconds <= 0.0 or args.sigma_m < 0.0:
        parser.error("fixed-delta-seconds must be positive and sigma-m non-negative")
    return args


def _spawn_uav(world, carla, altitude_m):
    blueprints = world.get_blueprint_library()
    # CARLA 0.9.16 has no native UAV/quadrotor blueprint. A small movable
    # non-vehicle prop gives the simulation a real CARLA actor without putting
    # a car into the scene; the visualizer supplies the UAV marker in the image.
    try:
        blueprint = blueprints.find("static.prop.mobile")
    except RuntimeError as exc:
        raise RuntimeError("CARLA has no movable non-vehicle actor for the kinematic UAV") from exc
    if blueprint.has_attribute("role_name"):
        blueprint.set_attribute("role_name", "nexus_uav")
    spawn_points = world.get_map().get_spawn_points()
    if not spawn_points:
        raise RuntimeError("CARLA map has no spawn points for the UAV")
    center_x = float(np.mean([item.location.x for item in spawn_points]))
    center_y = float(np.mean([item.location.y for item in spawn_points]))
    spawn_points = sorted(
        spawn_points,
        key=lambda item: (item.location.x - center_x) ** 2 + (item.location.y - center_y) ** 2,
    )
    for transform in spawn_points:
        uav_transform = carla.Transform(
            carla.Location(
                x=transform.location.x,
                y=transform.location.y,
                z=transform.location.z + altitude_m,
            ),
            transform.rotation,
        )
        uav = world.try_spawn_actor(blueprint, uav_transform)
        if uav is not None:
            return uav
    raise RuntimeError("no free CARLA static prop spawn point for the UAV")


def _collect_carla_trajectory(world, uav, args, carla):
    def local_position(index):
        time_s = index * args.fixed_delta_seconds
        return np.array([
            12.0 * np.sin(0.12 * time_s),
            9.0 * np.sin(0.08 * time_s + 0.5),
            0.15 * np.sin(0.20 * time_s),
        ])

    # CARLA static props expose a zero placeholder transform until their first
    # simulation tick. Synchronize once before defining the local ground frame.
    world.tick()
    uav_start = uav.get_transform().location
    ground_origin = carla.Location(
        x=uav_start.x, y=uav_start.y, z=uav_start.z - args.uav_altitude_m
    )

    def set_uav_position(position):
        uav.set_transform(carla.Transform(
            carla.Location(
                x=ground_origin.x + position[0],
                y=ground_origin.y + position[1],
                z=ground_origin.z + args.uav_altitude_m + position[2],
            ),
            carla.Rotation(yaw=float(np.degrees(np.arctan2(position[1], position[0])))),
        ))

    for index in range(args.warmup_frames):
        position = local_position(index - args.warmup_frames)
        set_uav_position(position)
        world.tick()

    positions = []
    timestamps = []
    velocities = []
    frame_ids = []
    previous_position = np.zeros(3, dtype=float)
    for index in range(args.frames):
        position = local_position(index + args.warmup_frames)
        set_uav_position(position)
        frame_id = world.tick()
        snapshot = world.get_snapshot()
        transform = uav.get_transform()
        velocity = (position - previous_position) / args.fixed_delta_seconds
        positions.append((
            float(transform.location.x - ground_origin.x),
            float(transform.location.y - ground_origin.y),
            float(transform.location.z - ground_origin.z),
        ))
        timestamps.append(int(snapshot.timestamp.elapsed_seconds * 1e9))
        velocities.append((float(velocity[0]), float(velocity[1]), float(velocity[2])))
        frame_ids.append(int(frame_id))
        previous_position = position

    positions = np.asarray(positions, dtype=float)
    path_length = float(np.sum(np.linalg.norm(np.diff(positions, axis=0), axis=1)))
    if path_length <= 1.0:
        raise RuntimeError(f"CARLA UAV did not move enough: path_length={path_length:.3f} m")
    return positions, np.asarray(timestamps, dtype=np.int64), velocities, frame_ids, path_length, ground_origin


def _anchors(args):
    x, y = args.anchor_half_width_m, args.anchor_half_height_m
    try:
        heights = tuple(float(value.strip()) for value in args.anchor_heights_m.split(","))
    except (AttributeError, TypeError, ValueError) as exc:
        raise ValueError("anchor-heights-m must contain four numeric values") from exc
    if len(heights) != 4 or not np.all(np.isfinite(heights)):
        raise ValueError("anchor-heights-m must contain four finite values")
    return [
        Anchor("A1", (-x, -y, heights[0])),
        Anchor("A2", (x, -y, heights[1])),
        Anchor("A3", (x, y, heights[2])),
        Anchor("A4", (-x, y, heights[3])),
    ]


def _run_algorithms(frames, positions, timestamps, *, initial_xyz=(0.0, 0.0, 2.0)):
    register_default_algorithms()
    metrics = {}
    estimate_rows = []
    for algorithm in ALGORITHMS:
        router = AlgorithmRouter(algorithm)
        reset_runner_state(router.spec.runner)
        estimates = []
        references = []
        valid_timestamps = []
        runtimes_ms = []
        for index, frame in enumerate(frames):
            result = router.run(observation_frame=frame, initial_xyz=initial_xyz)
            runtimes_ms.append(float(result.metadata.get("runtime_ms", float("nan"))))
            row = {
                "frame_seq": index,
                "sample_timestamp_ns": int(frame.timestamp_ns),
                "algorithm": algorithm,
                "valid": int(result.valid),
                "estimate_x_m": float(result.estimate[0]) if result.valid else float("nan"),
                "estimate_y_m": float(result.estimate[1]) if result.valid else float("nan"),
                "estimate_z_m": float(result.estimate[2]) if result.valid else float("nan"),
                "error_reason": "" if result.valid else result.metadata.get("error", "invalid"),
            }
            estimate_rows.append(row)
            if result.valid and np.asarray(result.estimate).size >= 3 and np.all(np.isfinite(result.estimate[:3])):
                estimates.append(result.estimate[:3])
                references.append(positions[index, :3])
                valid_timestamps.append(timestamps[index])

        valid_count = len(estimates)
        row_metrics = success_metrics(len(frames), valid_count, valid_timestamps)
        if valid_count:
            row_metrics.update(position_metrics(estimates, references))
            row_metrics["dimension"] = "3D"
            row_metrics["mae_m"] = float(np.mean(
                np.linalg.norm(np.asarray(estimates) - np.asarray(references), axis=1)
            ))
        else:
            row_metrics.update({
                "dimension": "3D", "rmse_m": float("nan"), "mae_m": float("nan"),
                "cep95_m": float("nan"),
            })
        row_metrics["runtime_mean_ms"] = float(np.nanmean(runtimes_ms))
        row_metrics["runtime_p95_ms"] = float(np.nanpercentile(runtimes_ms, 95))
        metrics[algorithm] = row_metrics
    return metrics, estimate_rows


def _write_outputs(args, anchors, frames, positions, velocities, frame_ids, metrics, estimates, metadata):
    output = args.output_dir.resolve()
    output.mkdir(parents=True, exist_ok=True)

    with (output / "observations.csv").open("w", encoding="utf-8", newline="") as stream:
        fields = [
            "frame_seq", "sample_timestamp_ns", "tag_id", "anchor_id",
            "anchor_x_m", "anchor_y_m", "anchor_z_m", "range_m", "stddev_m",
        ]
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader()
        for frame_seq, frame in enumerate(frames):
            for sample in frame.ranges:
                writer.writerow({
                    "frame_seq": frame_seq,
                    "sample_timestamp_ns": frame.timestamp_ns,
                    "tag_id": frame.tag_id,
                    "anchor_id": sample.anchor_id,
                    "anchor_x_m": sample.anchor_position_m[0],
                    "anchor_y_m": sample.anchor_position_m[1],
                    "anchor_z_m": sample.anchor_position_m[2],
                    "range_m": sample.range_m,
                    "stddev_m": sample.stddev_m,
                })

    with (output / "ground_truth.csv").open("w", encoding="utf-8", newline="") as stream:
        fields = [
            "frame_seq", "carla_frame", "sample_timestamp_ns", "x_m", "y_m", "z_m",
            "velocity_x_mps", "velocity_y_mps", "velocity_z_mps",
        ]
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader()
        for index, (position, velocity) in enumerate(zip(positions, velocities)):
            writer.writerow({
                "frame_seq": index,
                "carla_frame": frame_ids[index],
                "sample_timestamp_ns": frames[index].timestamp_ns,
                "x_m": position[0], "y_m": position[1], "z_m": position[2],
                "velocity_x_mps": velocity[0], "velocity_y_mps": velocity[1],
                "velocity_z_mps": velocity[2],
            })

    with (output / "estimates.csv").open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(estimates[0]))
        writer.writeheader()
        writer.writerows(estimates)

    payload = {"metadata": metadata, "anchors": [anchor.__dict__ for anchor in anchors], "metrics": metrics}
    with (output / "metrics.json").open("w", encoding="utf-8") as stream:
        json.dump(payload, stream, indent=2, ensure_ascii=False, allow_nan=True)
        stream.write("\n")
    return output


def main(argv=None):
    args = _parse_args(argv)
    try:
        import carla
    except ImportError as exc:
        raise RuntimeError("run with the Python environment containing CARLA 0.9.16") from exc

    client = carla.Client(args.host, args.port)
    client.set_timeout(30.0)
    client_version = client.get_client_version()
    server_version = client.get_server_version()
    if client_version != server_version:
        raise RuntimeError(f"CARLA version mismatch: client={client_version}, server={server_version}")
    world = client.get_world()
    if "sandbox-v29" not in world.get_map().name.lower():
        world = client.load_world("sandbox-v29")
    map_name = world.get_map().name
    if "sandbox-v29" not in map_name.lower():
        raise RuntimeError(f"CARLA loaded unexpected map: {map_name}")
    original_settings = world.get_settings()
    uav = None
    try:
        settings = world.get_settings()
        settings.synchronous_mode = True
        settings.fixed_delta_seconds = args.fixed_delta_seconds
        world.apply_settings(settings)
        uav = _spawn_uav(world, carla, args.uav_altitude_m)
        positions, timestamps, velocities, frame_ids, path_length, ground_origin = _collect_carla_trajectory(
            world, uav, args, carla
        )
    finally:
        if uav is not None:
            uav.destroy()
        world.apply_settings(original_settings)

    anchors = _anchors(args)
    frames = simulate_ranges(
        anchors,
        positions,
        timestamps,
        sigma_m=args.sigma_m,
        random_seed=args.random_seed,
        tag_id="carla_uav_uwb_tag",
        dimensions=3,
    )
    metrics, estimates = _run_algorithms(
        frames, positions, timestamps,
        initial_xyz=(0.0, 0.0, max(args.uav_altitude_m * 0.7, 1.0)),
    )
    metadata = {
        "carla_client_version": client_version,
        "carla_server_version": server_version,
        "carla_map": map_name,
        "coordinate_frame": "carla_uwb_local",
        "carla_local_origin_world_m": [
            float(ground_origin.x), float(ground_origin.y), float(ground_origin.z)
        ],
        "ground_truth_source": "CARLA kinematic UAV actor transform",
        "algorithm_input": "anchor coordinates, range_m, stddev_m, timestamp only",
        "ground_truth_used_by_algorithm": False,
        "tracked_entity": "uav_platform_base_link",
        "carla_uav_actor": {
            "blueprint": "static.prop.mobile",
            "role_name": "nexus_uav",
            "visual_mesh": "small non-vehicle prop; rendered UAV marker is in the visualization",
        },
        "range_model": "euclidean_3d",
        "dimensions": 3,
        "uav_altitude_m": args.uav_altitude_m,
        "frames": args.frames,
        "fixed_delta_seconds": args.fixed_delta_seconds,
        "range_sigma_m": args.sigma_m,
        "random_seed": args.random_seed,
        "carla_uav_path_length_m": path_length,
        "sources": {
            "positioning_algorithms_for_uwb_matlab": "2c24c478ae0c317840fec1c29631c15dbe29a630",
            "awesome_uwb_localization": "b3cd36e5d78da4daea2f350cfebeb6b8b8378810",
        },
    }
    output = _write_outputs(
        args, anchors, frames, positions, velocities, frame_ids, metrics, estimates, metadata
    )

    print(f"CARLA map: {metadata['carla_map']}")
    print(f"CARLA UAV path length: {path_length:.3f} m")
    print(f"{'Algorithm':<30} {'Valid':>8} {'RMSE(m)':>12} {'P95(m)':>12} {'Runtime(ms)':>12}")
    for algorithm in ALGORITHMS:
        row = metrics[algorithm]
        print(
            f"{algorithm:<30} {row['success_rate']:>8.1%} {row['rmse_m']:>12.5f} "
            f"{row.get('cep95_m', float('nan')):>12.5f} {row['runtime_mean_ms']:>12.4f}"
        )
    if any(not np.isfinite(row["rmse_m"]) or row["success_rate"] < 0.95 for row in metrics.values()):
        raise RuntimeError("one or more UWB algorithms failed the CARLA reproduction acceptance check")
    print(f"outputs: {output}")
    print("CARLA_UWB_REPRO_OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
