cmake_minimum_required(VERSION 3.8)
project(nexus_uwb_simulation)

find_package(ament_cmake REQUIRED)
find_package(ament_cmake_python REQUIRED)

ament_python_install_package(${PROJECT_NAME} PACKAGE_DIR src/${PROJECT_NAME})
install(PROGRAMS src/${PROJECT_NAME}/uwb_simulation_node.py
  DESTINATION lib/${PROJECT_NAME} RENAME uwb_simulation_node)
install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})
ament_package()
